name = "ai-chat-worker"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# Workers AI binding
[ai]
binding = "AI"

# KV namespace for session storage
[[kv_namespaces]]
binding = "CHAT_SESSIONS"
id = "5c20418b4b924a6dabe67c75610b4c08"
preview_id = "66791f36d34a430cb2e1ef5a6cfb8d82"

# Vectorize for RAG
[[vectorize]]
binding = "VECTORIZE"
index_name = "docs-index"

# KV namespace for message board
[[kv_namespaces]]
binding = "MESSAGE_BOARD"
id = "4b5e9ccd69394e74b92ea90ba05618ec"
preview_id = "53ab78ac60834482a3f5eca82389bd28"

[vars]
CORS_ORIGIN = "*"
